### ISSUE TITLE
请问能和你要下数据么，我错过了比赛报名，但是现在急需要用~！？

### ISSUE THREAD

**Issue by jasperyang** [panyang/fastText-for-AI-Challenger-Sentiment-Analysis#1]

**Comment by jasperyang** [comment]
472530484@qq.com 这是我的邮箱，如果你方便的话，发一份给我~我给你star了

**Comment by philharmonic77** [comment]
你好，我很想用原始数据试一试，但也是找了很久找不到。如果你方便的话，请给我发一份原始数据，多谢！我的邮箱是phil77@126.com

**Comment by panyang** [comment]
不好意思，好像很久了，才发现：从报名协议上来说，我是不能给你们提供数据的，搜了一下，有散落在github上的其他同学留存的数据：https://github.com/tinySean/Fine-grained-user-commenting-emotions
